### ISSUE TITLE
ResilientChangeTrackingEnabled = true has no effect

### ISSUE THREAD

**Issue by picrap** [dahall/Vanara#356] opened 2022-12-20 09:39 UTC
If RCT is not enabled, it can’t be enabled using the `ResilientChangeTrackingEnabled` property:
```csharp
using var v = VirtualDisk.Open(@"F:\Hyper-V\Windows XP\Virtual Hard Disks\Windows XP.vhdx", false, false, true);
v.ResilientChangeTrackingEnabled = false;
```
Does nothing (And it does not throw any error).

From a C++ program, invoking the native function works:
```C++
HANDLE vhdHandle;
_VIRTUAL_STORAGE_TYPE storageType{};
DWORD res = OpenVirtualDisk(&storageType, L"F:\\Hyper-V\\Windows XP\\Virtual Hard Disks\\Windows XP.vhdx",
        VIRTUAL_DISK_ACCESS_ALL, OPEN_VIRTUAL_DISK_FLAG_NONE, NULL, &vhdHandle);

SET_VIRTUAL_DISK_INFO setDiskInfo{};
setDiskInfo.ChangeTrackingEnabled = true;
setDiskInfo.Version = SET_VIRTUAL_DISK_INFO_CHANGE_TRACKING_STATE;
SetVirtualDiskInformation(vhdHandle, &setDiskInfo);
```

Please note that `ResilientChangeTrackingEnabled = false` (disabling RCT) actually works 😅, so RCT can be disabled, but not enabled.

**Comment by dahall** [comment] 2022-12-20 14:35
Please try the other `Open` overload. I believe the issue is related to the mask.
```cs
using var v = VirtualDisk.Open(filename, mask: VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_ALL);
v.ResilientChangeTrackingEnabled = false;
```

**Comment by dahall** [comment] 2022-12-20 22:36
Is your main application 64-bit?

**Comment by picrap** [comment] 2022-12-21 09:07
The platform target is set to “Any CPU” and I can’t find any other option that could relate to platform.

**Comment by dahall** [comment] 2022-12-21 15:17
Are you able to build your EXE with the target of `x86` and let me know if setting `ResilientChangeTrackingEnabled = true` still fails?

**Comment by picrap** [comment] 2022-12-21 15:27
That’s a win! It works in `x86`, fails in `x64` and `Any CPU`.

**Comment by dahall** [comment] 2022-12-21 23:53
Yep. Under 32-bit builds the structure aligns correctly so setting the structure field to `1` works. I'll fix it so it works on both 32 and 64 bit. Thanks for your help.

**Comment by dahall** [comment] 2022-12-23 21:02
This is now fixed

**Closed by dahall** 2022-12-23 21:02 UTC
