### ISSUE TITLE
LsaEnumerateAccountsWithUserRight throws when a privilege is specified

### ISSUE THREAD

**Issue by jcasale** [dahall/Vanara#302] opened 2022-07-01 20:54 UTC
**Describe the bug**
When calling `LsaEnumerateAccountsWithUserRight` with a value specified for `UserRights`, the function throws an `ArgumentException` with the message "Value does not fall within the expected range.".

The same call enumerates the sids correctly when `UserRights` is null.

I am targeting .net framework 4.6.2, but I have also tried 4.8 and I am seeing the same behavior. I have verified the problem exists on both Windows Server 2022 and Windows 11.

**What code is involved**
The following minimal repro describes the situation:
```cs
using System.Linq;
using Vanara.PInvoke;
using static Vanara.PInvoke.AdvApi32;

const string privilege = "SeDenyInteractiveLogonRight";
PSID[] psids;
using (var policy = LsaOpenPolicy(LsaPolicyRights.POLICY_ALL_ACCESS))
{
    psids = LsaEnumerateAccountsWithUserRight(policy, privilege).ToArray();
}
```

**Expected behavior**
The privilege is valid, I expect the call to enumerate all (if any) sids that are assigned.

**Comment by dahall** [comment] 2022-07-05 15:47
Thanks for helping me find an obscure bug in the `StringHelper` class that was the root cause of this error. The fix has been committed and a functional set of NuGet packages will be available shortly.

**Closed by dahall** 2022-07-05 15:47 UTC
