### ISSUE TITLE
Using User32.SystemParametersInfo with SPI_SETTHREADLOCALINPUTSETTINGS results in Type Mismatch ArguementException

### ISSUE THREAD

**Issue by paul-watson-squaredup** [dahall/Vanara#298] opened 2022-05-05 10:58 UTC
**Describe the bug**
When using the following code
`User32.SystemParametersInfo(User32.SPI.SPI_SETTHREADLOCALINPUTSETTINGS, true);`
a `ArgumentException: Type Mismatch` is always thrown

**What code is involved**
I believe the issue to be in `WinUser.System.cs` where `SPI_SETTHREADLOCALINPUTSETTINGS` has a `CorrespondingAction.Get` instead of `CorrespondingAction.Set` so when checking the argument filter it always fails because I'm using a Set action.

**Expected behavior**
`ArguementException: Type Mismatch` is not thrown

**Comment by dahall** [comment] 2022-05-05 13:39
Fixed in latest commit. You were correct on the cause. Thanks for debugging for me!

**Closed by dahall** 2022-05-05 13:39 UTC
