### ISSUE TITLE
Get Ole32.PROPERTYKEY.System.Recycle.DateDeleted from ShellItemPropertyStore will create a handle on .exe

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#214] opened 2021-03-07 07:13 UTC
**Describe the bug**
I want to get DateDeleted from RecycleBin item. So I have the code like this:
```csharp
if (Item.Properties.TryGetValue(Ole32.PROPERTYKEY.System.Recycle.DateDeleted, out object DeleteFileTime))
{
    Console.WriteLine($"DeleteTime: {Convert.ToString(((FILETIME)DeleteFileTime).ToInt64())}");
}
```
But I found that the read Ole32.PROPERTYKEY.System.Recycle.DateDeleted from Item.Properties will create a new handle on the .exe file. You could found that handle in Windows Resource Manager
![image](https://user-images.githubusercontent.com/42038175/110232170-271c9900-7f57-11eb-8c56-7ff19228371c.png)

So if Recycle Item is not .exe, it work fine.
If Recycle Item is .exe, but do not read Ole32.PROPERTYKEY.System.Recycle.DateDeleted, it work fine.

**What code is involved**
Here is the example code. Make sure you have .exe in your recycle bin:
[TestConsole.zip](https://github.com/dahall/Vanara/files/6096712/TestConsole.zip)

**Expected behavior**
Do not create any handle on the file because that will block me from restore or delete items in recyclebin

**Comment by dahall** [comment] 2021-03-07 18:27
I'll look into this, but my initial guess is that it is in the Shell's implementation of IPropertySet since I don't do anything with file handles and the property system. More to come...

**Comment by zhuxb711** [comment] 2021-03-08 03:07
Or is there any other way to get the deletion date? Any workaround?

**Comment by dahall** [comment] 2021-03-08 03:48
Are you a C++ programmer? If so, then seeing if the code from this [blog](https://devblogs.microsoft.com/oldnewthing/20110831-00/?p=9763) causes the same handle use could be useful. If it does, then it is for sure a system thing. If not, then we should look through the Vanara library to see what we're not releasing.

**Comment by zhuxb711** [comment] 2021-03-08 07:21
@dahall 
I'm not a C++ programmer. But I did found something.
Use this code will not create a handle on .exe
```csharp
using(ShellItem Item  = RecycleBin.GetItems().First())
{
     var temp = (Item.IShellItem as Shell32.IShellItem2).GetFileTime(Ole32.PROPERTYKEY.System.Recycle.DateDeleted).ToInt64();
}
```

**Comment by dahall** [comment] 2021-03-08 16:04
That convinces me further that the handle causing your earlier problem is created by the Shell. Since it appears you have found a workaround, I'll close the issue.

**Closed by dahall** 2021-03-08 16:04 UTC

**Comment by zhuxb711** [comment] 2021-03-29 09:23
@dahall I think it should not remain a handle on file after dispose

**Comment by zhuxb711** [comment] 2021-03-29 09:29
![image](https://user-images.githubusercontent.com/42038175/112816543-1a9de300-90b4-11eb-932f-6457506de70a.png)
[See here](https://stackoverflow.com/questions/8629718/how-do-i-use-ipropertystore-to-access-mp3-metadata-in-windows-with-c)

![image](https://user-images.githubusercontent.com/42038175/112816636-30130d00-90b4-11eb-874f-853fc4d8c135.png)

I think it might be cause by undocument method Release();
You don't call it in Dispose();

**Comment by dahall** [comment] 2021-03-29 13:48
That's just the COM IUnknown::Release method. I think the author was trying to be sarcastic with the comment. When using RCW (.NET's wrapper around COM objects) you typically don't release the instance since the runtime does that for you. I still think this is a problem caused by the Windows Shell code.
